# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    env:
      GPR_USER: "DNFneca"
      GPR_KEY: ${{secrets.GPR_KEY}}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Find and upload VBlocks file
      uses: actions/upload-artifact@v4
      with:
        name: VBlocks
        path: build/libs/VBlocks*.jar
        retention-days: 7
